version: '3.8'

services:
  hub:
    image: selenium/hub:latest
    expose:
      - 4444
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome-debug:3.141.59
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

  app:
    build: .
    container_name: fmovies-crawler
    depends_on:
      - hub
      - chrome
    environment:
      SELENIUM_REMOTE_URL: http://hub:4444/wd/hub
      IS_RUNNING_IN_DOCKER: 'yes'
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    networks:
      - selenium-grid

networks:
  selenium-grid:
