version: '3.8'

services:
  hub:
    image: selenium/hub:latest
    expose:
      - 4444
    ports:
      - '4444:4444'
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome-debug:3.141.59
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 8
      NODE_MAX_INSTANCES: 8
    shm_size: 2g
    ports:
      # VNC Viewer port
      - '7900:5900'
    depends_on:
      - hub
    networks:
      - selenium-grid

  redis:
    image: redis:6.0.10
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - redis

  app:
    build: .
    depends_on:
      - hub
      - chrome
    networks:
      - nest
      - selenium-grid
      - redis
    environment:
      SELENIUM_REMOTE_URL: http://hub:4444/wd/hub
      # Tells Fastify to listen on "0.0.0.0"
      IS_RUNNING_IN_DOCKER: 'yes'
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env

  # API Gateway
  openresty:
    image: openresty/openresty:1.19.3.2-alpine
    depends_on:
      - redis
      - app
    ports:
      - '${PORT-3000}:8080'
    networks:
      - nest
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - './nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './nginx/scripts:/scripts'

networks:
  nest:
  selenium-grid:
  redis:

volumes:
  redis-data:
